openapi: 3.0.1
info:
  title: NUIX ECC REST API Command Reference Case Utility API
  description: 'Welcome to the Nuix ECC REST API command reference. From here you can access all available ECC REST APIs.  You can also send REST commands to your running ECC Server, as well as view the responses.


    **Note\:** The Nuix ECC User Guide includes a gloassary which defines specialized terms such as `Case`, `Custodian` and `Target` which are mentioned throughout this command reference.


    **Note\:** This command reference has been updated for Nuix ECC version 9.12.0.'
  contact:
    name: Nuix
    url: https://nuix.github.io/sdk-docs/latest/
    email: APISupport@nuix.com
  license:
    name: Licence
    url: https://www.nuix.com/sites/default/files/20200210_EULA_v1.pdf
  version: ${customer.version}
servers:
- url: '{protocol}://{address}:{port}/api/ecc'
  variables:
    protocol:
      default: https
      description: protocol for communication
      enum:
      - http
      - https
    address:
      default: 127.0.0.1
      description: The location which the ECC resides
    port:
      default: '80'
      description: 80, 443 or alternative
security:
- BasicAuth: []
tags:
- name: Utility
paths:
  /v2/eccInstalled:
    get:
      tags:
      - Utility
      summary: Verify whether ECC Client or ECC Admin Console is installed on the specified computer.
      description: 'Verify whether ECC Client or ECC Admin Console is installed on the specified computer.

        If ECC Client or ECC Admin Console is installed, returns the name of the specified computer.

        If ECC client or ECC Admin Console is not installed, returns an ID 400 response.'
      operationId: eccInstalled
      parameters:
      - name: computerId
        in: query
        description: GUID which identifies the computer
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful query of ECC Installed
          content:
            application/json:
              schema:
                type: object
                properties:
                  computer name:
                    type: string
                    description: name of the computer identified by `computerId`
              example:
                computer name: 'someComputer.


                  local'
        '400':
          description: Invalid Computer ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standardResponse'
              example:
                code: 400
                id: 101
                message: Computer ID was not found
  /v2/license:
    get:
      tags:
      - Utility
      summary: Get ECC Server license information
      description: Returns the license info for the ECC Server specified in the URL.
      operationId: getServerLicense
      responses:
        '200':
          description: Successful query of ECC License
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/licenseResponse'
              example:
                hardwareId: ecc\\4\\ee5bb2fb\\ac3446ec-758b36fb-82f2cccf-51713e8e
                license: '-----BEGIN LICENCE-----

                  Key: XYZ100




                  hWtEQ2mXJMqU/E2v0LQtOTQqFThFYseE6ZgiLZpaBKqQUhnAtYENd1I0CkwR

                  YImmLrgSbof4VDXE3WqqnwWnN34yg6D36gJsaLR3k/Q0FZHi5/Ey72SI6KNZ

                  mC/y57I/g3ncMRFfeOkURvv2+t74AjblS8vF7L716UKEV9BsuQVjHJK1qhvQ

                  UirsUTFyFytTfT2N4Jh0iojvoPaacZBD8tGicJLetPF31rO8H6ABEz0wTNRs

                  2p2GqWg0efPY5joOaezL2/VKXbjcp9VNyHIaOsgCQnp9Bn+QuRJP7PAp9zTK

                  FQDgltafqLeI1xdGToirZECTU0LpM7o1Xlb27JSAKdCC27KcmcDY3J1qRcdK

                  +3xOWTuSgjjge3aZhls+mau+w0ila1HcCh/YKqUoExMun77aObJVwVg5cpX9

                  D2HPt8w=

                  -----END LICENCE-----'
                licenseDetails:
                  generatedBy: Generated by LicenceGenServer
                  generatedDate: Wed Sep 21 20:07:44 UTC 2022
                  created-at: '20220921200738'
                  deadline: '20221019000000'
                  ecc.clients_hard_cap: '60'
                  ecc.clients_soft_cap: '50'
                  id: XYZ100
                  keyid: ecc\\4\\ee5bb2fb\\ac3446ec-758b36fb-82f2cccf-51713e8e
                  owner: Testing
                  profile: ecc
  /v2/systemInfo:
    get:
      tags:
      - Utility
      summary: Get ECC Server system information
      description: Returns the system information for the ECC Server specified in the URL.
      operationId: getServerInfo
      responses:
        '200':
          description: Successful query of ECC Server information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/systemInfoResponse'
              example:
                eccVersion: 9.10.0.27511
                osName: Windows 10
                osVersion: '10'
                osBitness: 64-bit
                memoryGB: 16.9 GB
                NIC:
                - Name: eth3
                  Display-Name: PANGP Virtual Ethernet Adapter
                  IP-Address: 192.168.0.50
                - Name: eth4
                  Display-Name: Realtek USB GbE Family Controller
                  IP-Address: 192.168.0.51
                - Name: eth20
                  Display-Name: Hyper-V Virtual Ethernet Adapter
                  IP-Address: 192.168.0.52
                Volumes:
                - Type: NTFS
                  Free-Space: 629.9 GB
components:
  schemas:
    standardResponse:
      type: object
      properties:
        code:
          type: integer
          description: http response status code
        id:
          type: integer
          description: id of the affected Object
        message:
          type: string
          description: http status message
    systemInfoResponse:
      type: object
      properties:
        eccVersion:
          type: string
          description: The ECC version number of the ECC Server
        osName:
          type: string
          description: The name of the OS of the ECC Server
        osVersion:
          type: string
          description: The version of the OS of the ECC Server
        osBitness:
          type: string
          description: The bitness of the OS of the ECC Server, e.g. `64-bit`
        memoryGB:
          type: string
          description: The total physical memory of the ECC Server
        NIC:
          type: array
          description: array of network adapters on the ECC Server
          items:
            type: object
            properties:
              Name:
                type: string
                description: The network adapter system name, e.g. `eth3`
              Display-Name:
                type: string
                description: The network adapter display name, e.g. `Realtek USB GbE Family Controller`
              IP-Address:
                type: string
                description: The IPv4 address assigned to this network adapter
        Volumes:
          type: array
          description: array of volumes on the ECC Server
          items:
            type: object
            properties:
              Type:
                type: string
                description: The filesystem of this volume, e.g. `NTFS`
              Free-Space:
                type: string
                description: The total free space on this volume
    licenseResponse:
      type: object
      properties:
        hardwareId:
          type: string
          description: The license hardware ID
        license:
          type: string
          description: The license key, as PEM-encoded text
        licenseDetails:
          type: object
          properties:
            generatedBy:
              type: string
              description: The system which generated the license
            generatedDate:
              type: string
              description: The date (as a formatted string) when the license was generated.
            created-at:
              type: string
              description: The date (as an unformatted string) when the license was generated.
            deadline:
              type: string
              description: The date (as an unformatted string) when the license expires.
            ecc.clients_hard_cap:
              type: string
              description: The maximum number of ECC Clients which can be associated with this ECC Server.
            ecc.clients_soft_cap:
              type: string
              description: 'The number of ECC Clients which can be associated with this ECC Server

                without license warnings appearing in ECC Admin Console.'
            id:
              type: string
              description: The license ID
            keyid:
              type: string
              description: The license key ID
            owner:
              type: string
              description: The license owner
            profile:
              type: string
              description: The license profile, typically `ecc`
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
